FROM php:7.4-fpm

# Set working directory
WORKDIR /var/www

# Install dependencies

RUN apt-get update && apt-get install -y \
        php7.3-fpm php7.3-common php7.3-mysql php7.3-gmp php7.3-curl \
        php7.3-intl php7.3-mbstring php7.3-xmlrpc php7.3-gd php7.3-xml \
        php7.3-cli php7.3-zip php7.3-soap php7.3-imap php7.3-interbase php7.3-xdebug  \
        curl unzip git \
        openssl ca-certificates \
    --no-install-recommends


    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
RUN docker-php-ext-install gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents
COPY . /var/www

# Copy existing application directory permissions
COPY --chown=www:www . /var/www

# Change current user to www
USER www

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]

FROM debian:buster

# Install modules
#RUN apt-get install software-properties-common -y

RUN apt-get update && apt-get install -y \
        php7.3-fpm php7.3-common php7.3-mysql php7.3-gmp php7.3-curl \
        php7.3-intl php7.3-mbstring php7.3-xmlrpc php7.3-gd php7.3-xml \
        php7.3-cli php7.3-zip php7.3-soap php7.3-imap php7.3-interbase php7.3-xdebug  \
        curl unzip git \
        openssl ca-certificates \
    --no-install-recommends


#RUN cd ~ \
#    curl -sS https://getcomposer.org/installer -o composer-setup.php \
#    php composer-setup.php --install-dir=/usr/local/bin --filename=composer


#RUN docker-php-ext-install intl mbstring pdo_mysql exif gettext \
#    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
#    && docker-php-ext-install gd

##RUN pecl install -o -f xdebug \
##    && rm -rf /tmp/pear

#COPY ./install-composer.sh /

COPY ./php.ini /etc/php/7.3/fpm/
COPY ./www.conf /etc/php/7.3/fpm/pool.d/

    
#RUN sh /install-composer.sh && rm /install-composer.sh

RUN apt-get purge -y g++ \
    && apt-get autoremove -y \
    && rm -r /var/lib/apt/lists/* \
    && rm -rf /tmp/* 

EXPOSE 9000

RUN usermod -u 1000 www-data

#VOLUME /root/.composer
WORKDIR /var/www

RUN /etc/init.d/php7.3-fpm start 

RUN ln -s  /var/run/php/php7.3-fpm.sock /run/php/php7.3-fpm.sock

CMD ["/usr/sbin/php-fpm7.3", "-F"]


