<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'از صبر و شکیبایی شما سپاسگزاریم' => '',
    'با عرض پوزش سیستم در هنگام انجام  درخواست شما با خطا مواجه گردیده است.' => '',
    'خروج' => '',
    'خطای عدم دسترسی' => '',
    'داشبورد' => '',
    'درخواست شما نا معتبر است' => '',
    'صفحه مورد نظر شما پیدا نشد' => '',
    'متاسفانه خطای داخلی رخ داده است' => '',
    'متاسفانه در هنگام اجرای درخواست شما ، خطایی رخ داده است.
        لطفا دیگر این صفحه را درخواست ندهید 
        و اگر می توانید با مدیریت سایت تماس بگیرید.' => '',
    'مطلب حذف شده است!' => '',
    'مطلب یا صفحه مورد نظر شما حذف شده است. لطفا دوباره این صفحه را درخواست ندهید.' => '',
    'ممکن است مطلب مورد نظر شما حذف شده باشد' => '',
    'و یا نیاز است که شما وارد حساب کاربری خود گردید ' => '',
    'و یا پارامتر های ارسالی شما ناقص است' => '',
    'ورود' => '',
    'ویرایش پروفایل' => '',
    'پارامتر های ارسالی شما ناقص است' => '',
    'پنل مدیریت' => '',
    'کاربر گرامی !' => '',
    'کاربر گرامی!' => '',
    'کاربر گرامی!.' => '',
    'گزارش خطا در سیستم بطور خودکار ثبت گردیده است و در اسرع وقت توسط پشتیبان های فنی وبسایت بر طرف می گردد.' => '',
    'archive'=>'آرشیو',
];
